// react/src/components/Search.tsx
import { useState } from 'react';
import { Search, X, Filter, ArrowUpDown, LoaderCircle } from 'lucide-react';
import { setTypesAndData, type SComponent } from './appStore';

export function takeDecision({ data, query }: { data: any[], query: string }) {
  // Handle empty data
  if (!data || data.length === 0) return;

  // Get columns from first object
  let columns = Object.keys(data[0]);
  let namedColumn = '';
  const acc = columns.reduce((acc, col) => {
    if (typeof data[0][col] === 'string' || (data[0][col] instanceof Date || (typeof data[0][col] === 'string' && !isNaN(Date.parse(data[0][col]))))) {
      if (acc['string']) {
        acc['string'] += 1;
      }
      else {
        acc['string'] = 1;
        namedColumn = col;
      }
    } else if (typeof data[0][col] === 'number') {
      if (acc['number']) {
        acc['number'] += 1;
      }
      else {
        acc['number'] = 1;
      }
    } else {
      if (acc['unknown']) {
        acc['unknown'] += 1;
      } else {
        acc['unknown'] = 1;
      }
    }
    return acc;
  }, {} as Record<string, any>);
  console.log('Columns:', acc);
  columns = columns.filter(col => col !== namedColumn);
  columns.unshift(namedColumn);
  if (acc['string'] > 1 || acc['unknown'] > 0) {
    setTypesAndData(['table'], data, query, columns);
  }
  else if (acc['number'] > 1) {
    setTypesAndData(['line', 'table'], data, query, columns);
  } else if (acc['number'] === 1) {
    setTypesAndData(['bar', 'pie', 'donut', 'table'], data, query, columns);
  } else {
    setTypesAndData(['table'], data, query, columns);
  }
}

export default function SearchComponent() {
  const [query, setQuery] = useState('show unique transaction of sender name and amount');
  const [loading, setLoading] = useState(false);
  const clearSearch = () => {
    setQuery('');
  };
  const getData = () => {
    setLoading(true)
    setTypesAndData([], [], '', []);
    fetch('/api/get-query-result', { method: 'POST', body: JSON.stringify({ queryDescription: query }), headers: { 'Content-Type': 'application/json' } })
      .then(response => response.json())
      .then(data => {
        console.log(data);
        setLoading(false);
        takeDecision(data);
      })
      .catch(error => {
        console.error('Error fetching data:', error);
        setLoading(false);
      });

  };
  return (
    <div className="relative mb-6">
      <div className="relative">
        <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
        <textarea
          autoFocus
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Write your query description..."
          className="w-full pl-12 pr-12 py-4 text-lg border-2 border-gray-200 rounded-xl focus:border-blue-500 focus:outline-none transition-colors duration-200"
        />
        {query && (
          <div className="absolute right-12 top-1/2 transform -translate-y-1/2 flex items-center space-x-2">

            <button disabled={loading} onClick={getData} className="text-red-400 hover:text-red-600 transition-colors">
              {loading ? <LoaderCircle className="animate-spin text-blue-500 w-5 h-5" /> : <Search className="w-5 h-5" />}
            </button>
            <button
              onClick={clearSearch}
              className=" text-gray-400 hover:text-gray-600 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// angular/src/app/components/search/search.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DashboardService } from '../../services/dashboard.service';

@Component({
  selector: 'app-search',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css']
})
export class SearchComponent implements AfterViewInit {
  @ViewChild('searchInput') searchInput!: ElementRef<HTMLTextAreaElement>;
  
  query = 'show unique transaction of sender name and amount';
  loading = false;

  constructor(private dashboardService: DashboardService) {}

  ngAfterViewInit(): void {
    // Auto focus on the search input
    if (this.searchInput) {
      this.searchInput.nativeElement.focus();
    }
  }

  clearSearch(): void {
    this.query = '';
  }

  onEnterKey(event: any): void {
    if (event.shiftKey) {
      // Allow new line with Shift+Enter
      return;
    }
    // Prevent default Enter behavior and trigger search
    event.preventDefault();
    this.getData();
  }

  getData(): void {
    if (!this.query.trim()) return;
    
    this.loading = true;
    this.dashboardService.setTypesAndData([], [], '', []);
    
    this.dashboardService.getQueryResult(this.query)
      .subscribe({
        next: (data) => {
          console.log('Query result:', data);
          this.loading = false;
          this.dashboardService.takeDecision(data);
        },
        error: (error) => {
          console.error('Error fetching data:', error);
          this.loading = false;
        }
      });
  }
}

<div class="relative mb-6">
  <div class="relative">
    <!-- Search Icon -->
    <svg class="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
    
    <!-- Search Input -->
    <textarea
      [(ngModel)]="query"
      (keydown.enter)="onEnterKey($event)"
      placeholder="Write your query description..."
      class="w-full pl-12 pr-12 py-4 text-lg border-2 border-gray-200 rounded-xl focus:border-blue-500 focus:outline-none transition-colors duration-200"
      rows="3"
      #searchInput>
    </textarea>
    
    <!-- Action Buttons -->
    <div *ngIf="query" class="absolute right-12 top-1/2 transform -translate-y-1/2 flex items-center space-x-2">
      <!-- Search Button -->
      <button 
        [disabled]="loading" 
        (click)="getData()" 
        class="text-red-400 hover:text-red-600 transition-colors"
        title="Search">
        <svg *ngIf="!loading" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
        <svg *ngIf="loading" class="animate-spin w-5 h-5 text-blue-500" fill="none" viewBox="0 0 24 24">
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
      </button>
      
      <!-- Clear Button -->
      <button
        (click)="clearSearch()"
        class="text-gray-400 hover:text-gray-600 transition-colors"
        title="Clear">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>
  </div>
</div>
