// src/components/chat.jsx
import { useNavigate } from '@tanstack/react-router';
import { useState, useRef, useEffect } from 'react';
import {takeDecision} from "./Search"
import { MicIcon, SignalHighIcon, Loader2Icon } from 'lucide-react';
import { useSpeechRecognition } from './useSpeechRecognition';


export default function ChatPopup() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    { id: 1, text: "Hello! How can I help you today?", sender: "bot", timestamp: new Date() }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);
  const navigate = useNavigate();
  const [isLoading, setLoading] = useState(false);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };
  const {recognitionRef, text, interimText, setError, isListening, setIsListening, setText, setInterimText} =useSpeechRecognition()
  //console.log('intrimtext:', interimText)
  //console.log('text:', text)
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  useEffect(()=>{
    setInputValue(interimText||text)
  },[interimText, text])

  useEffect(() => {
    fetch('/api/get-bot-messages/' + (sessionStorage.getItem('userId')||'123'))
      .then(response => response.json())  
      .then(data => {
        if (data.messages && data.messages.length > 0) {
          const initialMessages = data.messages.map((msg, index) => ({
            id: index + 1,
            text: msg.text,
            sender: msg.sender,
            hasSql: msg.sender==='bot'? (msg.text.startsWith('SELECT') || msg.text.startsWith('select')): false,
            timestamp: new Date()
          }));
          setMessages(initialMessages);
        }
      })  
  }, []);

  const handleSendMessage = async () => {
    if (inputValue.trim() === '') return;

    const newMessage = {
      id: messages.length + 1,
      text: inputValue,
      sender: "user",
      timestamp: new Date()
    };

    setMessages(prev => [...prev, newMessage]);
    setInputValue('');
    setIsTyping(true);

    // Simulate bot response
    
      const botResponse = {
        id: messages.length + 2,
        text: "Thanks for your message! This is a demo response.",
        sender: "bot",
        timestamp: new Date()
      };
      fetch('/api/get-query-result', {
        method: 'POST', 
        headers: {
          'Content-Type': 'application/json', 
        },
        body: JSON.stringify({ user_input: newMessage.text, thread_id: sessionStorage.getItem('userId')||'123'})
      })
      .then(response => response.json())
      .then(data => {
        console.log('Bot response:', data);
        takeDecision(data);
        botResponse.text = data.query?data.query:'Your query description is not sufficient to generate a valid query.';
        botResponse.timestamp = new Date();
        setMessages(prev => [...prev, botResponse]);
        setIsTyping(false);})
      .catch(error => {
        console.error('Error fetching bot response:', error);
        setIsTyping(false);
      });
    
  };

  const loadSqlData = (sql) => {
    if (!sql) return; 
    setLoading(true);  
    fetch('/api/get-query-result2', {
      method: 'POST', 
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ query: sql })
    })
    .then(response => response.json())
    .then(data => {
      setLoading(false);
      data.sql= sql;
      takeDecision(data);
    })
    .catch(error => {
      setLoading(false);
      console.error('Error fetching SQL data:', error);
    });
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      handleSendMessage();
    }
  };

  const formatTime = (date) => {
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  const toggleListening = () => {
    try {
      if (isListening) {
        recognitionRef.current.stop();
      } else {
        setText('');
        setInterimText('');
        setError('');
        recognitionRef.current.start();
      }
      setIsListening(!isListening);
    } catch (err) {
      setError(`Failed to ${isListening ? 'stop' : 'start'} speech recognition: ${err.message}`);
    }
  };

  return (
    <div className={`fixed top-4 right-4 ${isOpen?'z-50':''}`}>
      {/* Chat Toggle Button */}
      <button
        onClick={() =>{
           setIsOpen(!isOpen);
           if(window.location.pathname !== '/dashboard') {
            console.log('Redirecting to dashboard');
             navigate({ 
        to: '/dashboard',
        replace: true 
      })
           }
        }}
        className={`mb-4 -mt-2 p-3 rounded-full shadow-lg transition-all duration-300 transform hover:scale-110 ${
          isOpen 
            ? 'bg-red-500 hover:bg-red-600 text-white' 
            : 'bg-blue-500 hover:bg-blue-600 text-white'
        }`}
      >
        {isOpen ? (
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        ) : (
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
        )}
      </button>

      {/* Chat Window */}
      <div className={`bg-white rounded-lg shadow-2xl border transition-all duration-300 transform ${
        isOpen 
          ? 'opacity-100 scale-100 translate-y-0' 
          : 'opacity-0 scale-95 translate-y-4 pointer-events-none'
      }`} style={{ width: '400px', height: '500px' }}>
        
        {/* Chat Header */}
        <div className="bg-blue-500 text-white p-4 rounded-t-lg flex justify-between items-center">
          <div className="flex items-center space-x-2">
            <div className="w-3 h-3 bg-green-400 rounded-full"></div>
            <h3 className="font-semibold">Chat Support</h3>
          </div>
          <button
            onClick={() => setIsOpen(false)}
            className="text-blue-200 hover:text-white transition-colors"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
        </div>

        {/* Messages Container */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4" style={{ height: '360px' }}>
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div
                className={`max-w-xs px-4 py-2 rounded-lg ${
                  message.sender === 'user'
                    ? 'bg-blue-500 text-white rounded-br-none'
                    : 'bg-gray-200 text-gray-800 rounded-bl-none relative group'
                }`}
              >
                {message.hasSql ?<button
                disabled={isLoading}
          onClick={() => loadSqlData(message.text)}
          title='Click to load data'
          className="p-1 cursor-pointer opacity-0 group-hover:opacity-100 absolute -top-1 -right-1 text-red-400 hover:text-red-600 transition-colors"
        >
          {isLoading?<Loader2Icon className={` w-4 h-4`}/>:<SignalHighIcon className={` w-4 h-4`} />}
        </button>:null}
                <p className="text-sm">{message.text}</p>
                <p className={`text-xs mt-1 ${
                  message.sender === 'user' ? 'text-blue-200' : 'text-gray-500'
                }`}>
                  {formatTime(message.timestamp)}
                </p>
              </div>
            </div>
          ))}
          
          {/* Typing Indicator */}
          {isTyping && (
            <div className="flex justify-start">
              <div className="bg-gray-200 text-gray-800 px-4 py-2 rounded-lg rounded-bl-none">
                <div className="flex space-x-1">
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-pulse"></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-pulse" style={{ animationDelay: '0.2s' }}></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-pulse" style={{ animationDelay: '0.4s' }}></div>
                </div>
              </div>
            </div>
          )}
          
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="border-t p-4">
          <div className="flex space-x-2">
            <input
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Type your message..."
              className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            />
            <button
              onClick={handleSendMessage}
		          disabled={inputValue.trim() === ''}
              className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
              </svg>
            </button>
            <button
              onClick={toggleListening}
              className={`px-4 py-2 ${isListening?'bg-red-500':'bg-blue-500'} text-white rounded-lg hover:${isListening?'bg-red-600':'bg-blue-600'} focus:outline-none focus:ring-2 focus:${isListening?'ring-red-500':'ring-blue-500'} disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors`}
            >
              <MicIcon className="w-5 h-5" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// angular/src/app/components/chat/chat.component.ts
import { Component, OnInit, ElementRef, ViewChild, AfterViewChecked, OnDestroy } from '@angular/core';
import { CommonModule, formatDate } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ChatService, Message } from '../../services/chat.service';
import { DashboardService } from '../../services/dashboard.service';
import { SpeechRecognitionService } from '../../services/speech-recognition.service';
import { Subscription } from 'rxjs';
import { LucideAngularModule, SignalHighIcon, Loader2Icon, BarChart3, TrendingUp, DonutIcon, PieChart, Grid3X3 } from 'lucide-angular';
import { TableComponentComponent } from '../table-component/table-component.component';
import { LineChartComponent } from '../chart-components/line-chart/line-chart.component';
import { BarChartComponent } from '../chart-components/bar-chart/bar-chart.component';
import { PieChartComponent } from '../chart-components/pie-chart/pie-chart.component';

@Component({
  selector: 'app-chat',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.css']
})
export class ChatComponent implements OnInit, AfterViewChecked, OnDestroy {
  @ViewChild('messagesContainer') messagesContainer!: ElementRef;

  isOpen = false;
  messages: Message[] = [
    { id: 1, text: 'Hello! How can I help you today?', sender: 'bot', timestamp: new Date() },
  ];
  inputValue = '';
  isTyping = false;
  isLoading = false;
  private transcriptSubscription: Subscription;
  private errorSubscription: Subscription;
  get components() {
    return this.dashboardService.dashboardState.value.types.map(type => {
      switch (type) {
        case 'bar': return { type: 'bar', icon: BarChart3, name: 'Bar Chart', component: BarChartComponent };
        case 'line': return { type: 'line', icon: TrendingUp, name: 'Line Chart', component: LineChartComponent };
        case 'pie': return { type: 'pie', icon: PieChart, name: 'Pie Chart', component: PieChartComponent };
        case 'donut': return { type: 'donut', icon: DonutIcon, name: 'Donut Chart', component: PieChartComponent };
        case 'table': return { type: 'table', icon: Grid3X3, name: 'Table', component: TableComponentComponent };
        default: return { type: 'unknown', icon: BarChart3, name: 'Unknown', component: null };
      }
    })
  }
  get error() {
    return this.dashboardService.dashboardState.value.error;
  }
  constructor(
    private chatService: ChatService,
    private dashboardService: DashboardService,
    private router: Router,
    public speechRecognitionService: SpeechRecognitionService
  ) {
    this.transcriptSubscription = this.speechRecognitionService.transcript$.subscribe(
      transcript => {
        this.inputValue = transcript;
      }
    );
    this.errorSubscription = this.speechRecognitionService.error$.subscribe(
      error => {
        console.error(error);
      }
    );
  }

  ngOnInit(): void {
    this.loadChatHistory();
  }

  ngAfterViewChecked(): void {
    this.scrollToBottom();
  }

  private loadChatHistory(): void {
    console.log('Loading chat history...');
    const userId = sessionStorage.getItem('userId') || '123';
    this.chatService.getBotMessages(userId).subscribe({
      next: (data) => {
        if (data.messages && data.messages.length > 0) {
          const initialMessages = data.messages.map((msg: any, index: number) => ({
            id: index + 1,
            text: msg.text,
            sender: msg.sender,
            hasSql: msg.sender === 'bot' ? (msg.text.startsWith('SELECT') || msg.text.startsWith('select')) : false,
            timestamp: new Date()
          }));
          this.messages = initialMessages;
        }
      },
      error: (error) => {
        console.error('Error loading chat history:', error);
      }
    });
  }

  private scrollToBottom(): void {
    if (this.messagesContainer) {
      const element = this.messagesContainer.nativeElement;
      element.scrollTop = element.scrollHeight;
    }
  }

  toggleChat(): void {
    this.isOpen = !this.isOpen;
    if (this.isOpen && this.router.url !== '/dashboard') {
      console.log('Redirecting to dashboard');
      this.router.navigate(['/dashboard'], { replaceUrl: true });
    }
  }

  closeChat(): void {
    this.isOpen = false;
  }

  handleSendMessage(): void {
    if (this.inputValue.trim() === '') return;

    const newMessage: Message = {
      id: this.messages.length + 1,
      text: this.inputValue,
      sender: 'user',
      timestamp: new Date(),
    };

    this.messages.push(newMessage);
    const userInput = this.inputValue;
    this.inputValue = '';
    this.isTyping = true;

    // Send message to backend
    const threadId = sessionStorage.getItem('userId') || '123';
    this.chatService.sendMessage(userInput, threadId).subscribe({
      next: (data) => {
        console.log('Bot response:', data);
        this.dashboardService.takeDecision(data);

        const botResponse: Message = {
          id: this.messages.length + 1,
          text: data.query ? data.query : 'Your query description is not sufficient to generate a valid query.',
          sender: 'bot',
          hasSql: data.query ? (data.query.startsWith('SELECT') || data.query.startsWith('select')) : false,
          timestamp: new Date()
        };

        this.messages.push(botResponse);
        this.isTyping = false;
      },
      error: (error) => {
        console.error('Error sending message:', error);
        this.dashboardService.takeDecision(error);
        this.isTyping = false;
      }
    });
  }

  loadSqlData(sql: string): void {
    if (!sql) return;

    this.isLoading = true;
    this.chatService.executeQuery(sql).subscribe({
      next: (data) => {
        this.isLoading = false;
        data.query = sql;
        this.dashboardService.takeDecision(data);
      },
      error: (error) => {
        this.isLoading = false;
        error.query = sql;
        this.dashboardService.takeDecision(error);
        console.error('Error executing SQL:', error);
      }
    });
  }

  handleKeyPress(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.handleSendMessage();
    }
  }

  formatTime(date: Date): string {
    return formatDate(date, 'shortTime', 'en-US');
  }

  toggleListening() {
    if (this.speechRecognitionService.isListening) {
      this.speechRecognitionService.stop();
    } else {
      this.speechRecognitionService.start();
    }
  }

  get query(): string {
    return this.dashboardService.dashboardState.value.query || '';
  }
  addComponent(type: string): void {
    console.log('Adding component of type:', type);
    const componentType = this.components.find(ct => ct.type === type);
    const dashboard = this.dashboardService.getDashboard();
    if (componentType && dashboard.columns.length > 0) {
      const newComponent = {
        id: Number(new Date().getTime()),
        type: type as any,
        title: componentType.name,
        query: dashboard.query || '',
        data: dashboard.data,
        columns: dashboard.columns,
        user_id: sessionStorage.getItem('userId') || ''
      };

      console.log('Adding new component:', newComponent);
      this.dashboardService.addComponent(newComponent);

      // Save to server if user is logged in
      if (newComponent.user_id) {
        const serverComponent = { ...newComponent };
        (serverComponent as any).columns = (serverComponent.columns || []).join(',');
        delete (serverComponent as any).data;

        this.dashboardService.createDashboardComponent(serverComponent).subscribe({
          next: (response) => {
            console.log('Component saved to server:', response);
            // Update the component with server-generated ID
            const updatedComponent = { ...newComponent, id: response.dashboard.id };
            this.dashboardService.removeComponent(newComponent.id);
            this.dashboardService.addComponent(updatedComponent);
          },
          error: (error) => {
            console.error('Error saving component:', error);
          }
        });
      }
    }
  }
  ngOnDestroy() {
    this.transcriptSubscription.unsubscribe();
    this.errorSubscription.unsubscribe();
  }
}

<div [class]="'fixed top-4 right-4 ' + (isOpen ? 'z-50' : '')">
  <!-- Chat Toggle Button -->
  <button
    (click)="toggleChat()"
    [class]="
      'mb-4 -mt-2 p-3 rounded-full shadow-lg transition-all duration-300 transform hover:scale-110 ' +
      (isOpen
        ? 'bg-red-500 hover:bg-red-600 text-white'
        : 'bg-blue-500 hover:bg-blue-600 text-white')
    "
  >
    <ng-container *ngIf="isOpen; else chatIcon">
      <svg
        class="w-6 h-6"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          d="M6 18L18 6M6 6l12 12"
        />
      </svg>
    </ng-container>
    <ng-template #chatIcon>
      <svg
        class="w-6 h-6"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
        />
      </svg>
    </ng-template>
  </button>

  <!-- Chat Window -->
  <div
    [class]="
      'bg-white rounded-lg shadow-2xl border transition-all duration-300 transform ' +
      (isOpen
        ? 'opacity-100 scale-100 translate-y-0'
        : 'opacity-0 scale-95 translate-y-4 pointer-events-none')
    "
    style="width: 400px; height: 500px"
  >
    <!-- Chat Header -->
    <div
      class="bg-blue-500 text-white p-4 rounded-t-lg flex justify-between items-center"
    >
      <div class="flex items-center space-x-2">
        <div class="w-3 h-3 bg-green-400 rounded-full"></div>
        <h3 class="font-semibold">Chat Support</h3>
      </div>
      <button
        (click)="closeChat()"
        class="text-blue-200 hover:text-white transition-colors"
      >
        <svg
          class="w-5 h-5"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            d="M19 9l-7 7-7-7"
          />
        </svg>
      </button>
    </div>

    <!-- Messages Container -->
    <div
      class="flex-1 overflow-y-auto p-4 space-y-4"
      style="height: 360px"
      #messagesContainer
    >
      <div
        *ngFor="let message of messages"
        [class]="
          'flex ' +
          (message.sender === 'user' ? 'justify-end' : 'justify-start')
        "
      >
        <div
          [class]="
            'max-w-xs px-4 py-2 rounded-lg relative group ' +
            (message.sender === 'user'
              ? 'bg-blue-500 text-white rounded-br-none'
              : 'bg-blue-200 text-gray-800 rounded-bl-none')
          "
        >
          <button
            *ngIf="message.hasSql && message.text !== query"
            [disabled]="isLoading"
            (click)="loadSqlData(message.text)"
            title="Click to load data"
            class="absolute -top-1 -right-1 p-1 cursor-pointer opacity-0 group-hover:opacity-100 text-red-400 hover:text-red-600 transition-colors"
          >
            <svg
              *ngIf="!isLoading"
              class="w-4 h-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M13 10V3L4 14h7v7l9-11h-7z"
              />
            </svg>
            <svg
              *ngIf="isLoading"
              class="w-4 h-4 animate-spin"
              fill="none"
              viewBox="0 0 24 24"
            >
              <circle
                class="opacity-25"
                cx="12"
                cy="12"
                r="10"
                stroke="currentColor"
                strokeWidth="4"
              ></circle>
              <path
                class="opacity-75"
                fill="currentColor"
                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
              ></path>
            </svg>
          </button>
          <div class="text-sm">
            <ng-container
              *ngIf="
                message.hasSql && message.text === query;
                else showMessageText
              "
            >
              <div class="flex flex-wrap gap-2 mb-2">
                <button
                  *ngFor="let component of components"
                  (click)="addComponent(component.type)"
                  class="px-2 py-1 text-xs rounded cursor-pointer bg-gray-100 hover:text-fuchsia-700 transition-colors"
                >
                  <lucide-angular
                    [img]="component.icon"
                    class="w-4 h-4 inline-block mr-1"
                  />
                  {{ component.name }}
                </button>
              </div>
              <div
                *ngIf="components.length === 0 && error"
                class="text-red-500"
              >
                {{ error }}
              </div>
            </ng-container>
            <ng-template #showMessageText>
              <span>{{ message.text }}</span>
            </ng-template>
            <!-- <ng-container *ngIf="message.hasSql && message.text === query">
              <div class="flex flex-wrap gap-2 mb-2">
                <button
                  *ngFor="let component of components"
                  (click)="addComponent(component.type)"
                  class="px-2 py-1 text-xs rounded cursor-pointer bg-gray-100 hover:text-fuchsia-700 transition-colors"
                >
                  <lucide-angular
                    [img]="component.icon"
                    class="w-4 h-4 inline-block mr-1"
                  />
                  {{ component.name }}
                </button>
              </div>

            </ng-container>
            <ng-container *ngIf="message.hasSql && message.text !== query">
              <span>{{ message.text }}</span>
            </ng-container> -->
          </div>
          <p
            [class]="
              'text-xs mt-1 ' +
              (message.sender === 'user' ? 'text-blue-200' : 'text-gray-500')
            "
          >
            {{ formatTime(message.timestamp) }}
          </p>
        </div>
      </div>

      <!-- Typing Indicator -->
      <div *ngIf="isTyping" class="flex justify-start">
        <div
          class="bg-gray-200 text-gray-800 px-4 py-2 rounded-lg rounded-bl-none"
        >
          <div class="flex space-x-1">
            <div class="w-2 h-2 bg-gray-400 rounded-full animate-pulse"></div>
            <div
              class="w-2 h-2 bg-gray-400 rounded-full animate-pulse"
              style="animation-delay: 0.2s"
            ></div>
            <div
              class="w-2 h-2 bg-gray-400 rounded-full animate-pulse"
              style="animation-delay: 0.4s"
            ></div>
          </div>
        </div>
      </div>
    </div>

    <!-- Input Area -->
    <div class="border-t p-4">
      <div class="flex space-x-2">
        <button (click)="toggleListening()" class="focus:outline-none">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            [ngClass]="{
              'text-red-500': speechRecognitionService.isListening,
              'text-gray-500': !speechRecognitionService.isListening
            }"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z"
            />
          </svg>
        </button>
        <input
          type="text"
          [(ngModel)]="inputValue"
          (keypress)="handleKeyPress($event)"
          placeholder="Type your message..."
          class="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        />
        <button
          (click)="handleSendMessage()"
          [disabled]="inputValue.trim() === ''"
          class="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
        >
          <svg
            class="w-5 h-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
            />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>
