// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { ChatComponent } from './components/chat/chat.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive, ChatComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Flask Angular App';
}

<div class="min-h-screen bg-gray-50">
  <!-- Navigation -->
  <nav class="bg-white shadow-sm border-b">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        <div class="flex items-center space-x-8">
          <div class="flex space-x-4">
            <a
              routerLink="/"
              class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
              routerLinkActive="text-blue-600 bg-blue-50"
              [routerLinkActiveOptions]="{ exact: true }"
            >
              Home
            </a>

            <a
              routerLink="/dashboard"
              class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
              routerLinkActive="text-blue-600 bg-blue-50"
            >
              Dashboard
            </a>
            <a
              routerLink="/login"
              class="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
              routerLinkActive="text-blue-600 bg-blue-50"
            >
              Login
            </a>
          </div>
        </div>
        <app-chat></app-chat>
      </div>
    </div>
  </nav>

  <!-- Main content -->
  <main class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <router-outlet></router-outlet>
  </main>
</div>

// src/App.jsx
import React from 'react';
import {
  createRouter,
  createRoute,
  createRootRoute,
  Link,
  Outlet,
  RouterProvider,
  //useNavigate,
  //useParams,
  //useSearch,
  //redirect
} from '@tanstack/react-router';

import HomePage from './components/HomePage';
import CounterPage from './components/CounterPage';
import Counter2Page from './components/Counter2Page';
import DashboardPage from './components/DashboardPage';
// Root route component
function RootComponent() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Navigation */}
      <nav className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center space-x-8">
              {/* <Link 
                to="/" 
                className="text-xl font-bold text-blue-600 hover:text-blue-800"
              >
                TanStack Router Demo
              </Link> */}
              <div className="flex space-x-4">
                <Link 
                  to="/" 
                  className="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
                  activeProps={{ className: "text-blue-600 bg-blue-50" }}
                >
                  Home
                </Link>
                <Link 
                  to="/counter1" 
                  className="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
                  activeProps={{ className: "text-blue-600 bg-blue-50" }}
                >
                  Counter1
                </Link>
                <Link 
                  to="/counter2" 
                  className="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
                  activeProps={{ className: "text-blue-600 bg-blue-50" }}
                >
                  Counter2
                </Link>
                <Link 
                  to="/dashboard" 
                  className="text-gray-700 hover:text-blue-600 px-3 py-2 rounded-md text-sm font-medium"
                  activeProps={{ className: "text-blue-600 bg-blue-50" }}
                >
                  Dashboard
                </Link>
              </div>
            </div>
          </div>
        </div>
      </nav>

      {/* Main content */}
      <main className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <Outlet />
      </main>
    </div>
  );
}

// Define routes
const rootRoute = createRootRoute({
  component: RootComponent,
});

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: HomePage,
});

const aboutRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/counter1',
  component: CounterPage,
});

const usersRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/counter2',
  component: Counter2Page,
});

const dashboardRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/dashboard',
  component: DashboardPage,
});


// Create route tree
const routeTree = rootRoute.addChildren([
  indexRoute,
  aboutRoute,
  usersRoute,
  dashboardRoute
]);

// Create router
const router = createRouter({ routeTree });

// Main App component
export default function App() {
  return <RouterProvider router={router} />;
}
